name: Generate README (Inline)

on:
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
      
      - name: Checkout assets branch
        uses: actions/checkout@v4
        with:
          ref: assets
          path: assets
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Generate README
        run: |
          # Copy files to working directory
          mkdir -p workspace/data
          cp -r assets/data/readme.json workspace/data/
          cp -r assets/scripts workspace/
          cp -r main/* workspace/ 2>/dev/null || true
          
          # Generate README
          cd workspace
          node scripts/generate-readme.js
          
          # Show what was generated
          echo "=== Generated README.md ==="
          head -50 README.md
      
      - name: Upload README as artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-readme
          path: workspace/README.md
      
      - name: Create Pull Request
        run: |
          # Copy generated README to main
          cp workspace/README.md main/README.md
          
          # Check for changes
          cd main
          if git diff --quiet README.md; then
            echo "No changes to README.md"
          else
            echo "README.md has changes, creating PR..."
            
            # Create a new branch
            BRANCH_NAME="update-readme-$(date +%Y%m%d-%H%M%S)"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git checkout -b $BRANCH_NAME
            git add README.md
            git commit -m "Auto-generate README from data.json"
            git push origin $BRANCH_NAME
            
            # Create PR using GitHub CLI
            gh pr create \
              --title "Auto-update: README.md from data.json" \
              --body "This PR was automatically generated from the \`data.json\` file on the \`assets\` branch.
              
              ## Changes
              - Updated README.md based on latest data
              
              ## Source
              - Data: \`assets\` branch → \`data.json\`
              - Generated by: GitHub Actions workflow
              
              Please review the changes before merging." \
              --base main \
              --head $BRANCH_NAME
          fi
        env:
          GH_TOKEN: ${{ github.token }}